"""Deterministic pre-generation safety gate for Fit Bot — port of the Dart
`safety_gate.dart`, kept 1:1 in sync with it.

The LLM is never trusted to police medical/off-topic/abusive content
itself. This plain keyword/regex check runs BEFORE generation and can skip
it entirely, which is what actually guarantees the safety behavior.
"""

import re

_SPACED_LETTERS = re.compile(r"\b(?:[a-zA-Z]\s+){2,}[a-zA-Z]\b")
_LEET_MAP = str.maketrans({"1": "i", "3": "e", "4": "a", "0": "o", "@": "a", "$": "s"})


def normalize_for_matching(text: str) -> str:
    """Collapses adversarial obfuscation before any keyword list below ever
    sees the text — spacing out letters ("s t e r o i d s") and leetspeak
    substitution ("stup1d", "garb@ge") both slip straight past plain
    substring matching otherwise."""
    low = text.lower()
    low = _SPACED_LETTERS.sub(lambda m: m.group(0).replace(" ", ""), low)
    return low.translate(_LEET_MAP)


MEDICAL_KEYWORDS = [
    "steroid", "anabolic", "sarms", "sarm ", "clenbuterol", "trenbolone", "dianabol",
    "anavar", "winstrol", "hgh", "human growth hormone", "testosterone cycle",
    "peptide cycle", "insulin dosage", "prescription", "diagnos", "chemotherapy",
    "antidepressant", "dosage of", "mg per day", "injectable", "medication",
    "chronic illness", "chronic pain", "disease", "pregnan", "depress", "anxiety disorder",
    "mental health", "suicid", "self harm", "injured", "torn ", "tore my", "sprain",
    "fracture", "surgery", "blood pressure medic", "diabetes", "asthma inhaler",
    "eating disorder", "cancer",
]

OFF_TOPIC_KEYWORDS = [
    "stock market", "election", "politic", "hack into", "wifi network", "religion",
    "movie", "essay about", "capital of", "javascript", "python script", "code bug",
    "football match", "cricket match", "invest", "crypto", "bitcoin", "recipe for pasta",
    "write me a poem", "translate this", "my taxes", "tax return", "weather today",
    "relationship advice", "homework help", "math problem", "python homework", "my code",
    "what's the weather", "weather like", "my homework", "unrelated question",
    "not fitness related", "off topic", "ignore previous instructions",
    "ignore all previous", "ignore your instructions",
]

# Anything asking for a private detail we were never given. Kept
# deliberately broad — the model must never be allowed to invent a phone
# number, address, or bank/financial detail for the owner just because it
# sounds plausible.
PERSONAL_INFO_KEYWORDS = [
    "phone number", "cell number", "personal cell", "mobile number", "whatsapp number",
    "contact number", "personal number", "home address", "personal address",
    "residential address", "where does junaid live", "where do you live",
    "where he lives", "what neighborhood", "what city does", "which city does",
    "bank account", "bank details", "iban", "credit card", "debit card",
    "cnic", "national id", "id card number", "social security", "passport number",
    "his wife", "his kids", "his children", "his family", "is he married",
    "is junaid married", "junaid's wife", "junaid's family", "junaid's kids",
]

# Contact/email requests get a fixed, exact answer — never generated by the
# LLM, since a single wrong character breaks an email address.
CONTACT_KEYWORDS = [
    "owner's email", "owner email", "junaid's email", "junaid email",
    "contact junaid", "contact the owner", "contact hybridfit", "hybridfit email",
    "hybridfit's email", "how can i contact", "how do i contact", "get in touch with",
    "reach out to junaid", "reach junaid", "contact information", "contact info",
    "email address", "official email", "your email", "what is your email",
]

# Obfuscated-profanity regex (letter repeats / symbol substitution tolerant)
# — checked against the already-normalized text, not the raw string.
_ABUSIVE_PATTERNS = [
    re.compile(r"f+\W*u+\W*c+\W*k+", re.IGNORECASE),
    re.compile(r"sh+\W*i+\W*t+", re.IGNORECASE),
    re.compile(r"b+\W*i+\W*t+\W*c+\W*h+", re.IGNORECASE),
    re.compile(r"a+\W*s+\W*s+\W*h+\W*o+\W*l+\W*e+", re.IGNORECASE),
    re.compile(r"\bidiot\b", re.IGNORECASE),
    re.compile(r"\bstupid\b", re.IGNORECASE),
    re.compile(r"\buseless\b", re.IGNORECASE),
    re.compile(r"\bgarbage\b", re.IGNORECASE),
    re.compile(r"\bshut up\b", re.IGNORECASE),
    re.compile(r"\bkutt[ae]\b", re.IGNORECASE),
    re.compile(r"\bbewaqoof\b", re.IGNORECASE),
    re.compile(r"\bharaam(zada|i)\b", re.IGNORECASE),
]

# Catches the model claiming to *be* Junaid instead of an AI he built —
# a small fine-tuned model's persona adherence is unreliable even with an
# explicit system prompt saying "you are an AI, not Muhammad Junaid
# himself", so this is checked post-generation too (see is_false_identity_claim)
# rather than trusted to the prompt alone.
_FALSE_IDENTITY_CLAIM = re.compile(
    r"\b(i'?m|i am|this is|it'?s|it is|my name is)\s+(muhammad\s+)?junaid\b|\bjunaid\s+here\b",
    re.IGNORECASE,
)

OWNER_CONTACT_EMAIL = "hybridstrengthnfitness@gmail.com"

ENGLISH_ONLY_REDIRECT = (
    "I can only understand English right now. Please type your message in English and I'll be happy to help."
)
BOT_IDENTITY_REDIRECT = (
    "I'm HybridFit Assistant, an AI fitness coach built by Muhammad Junaid for the HybridFit "
    "app -- not Junaid himself. How can I help with your training today?"
)
PERSONAL_INFO_REDIRECT = (
    f"I don't have that information to share. For anything else, you can reach out at {OWNER_CONTACT_EMAIL}."
)
CONTACT_REDIRECT = f"You can reach Muhammad Junaid and the HybridFit team at {OWNER_CONTACT_EMAIL}."
MEDICAL_REDIRECT = (
    "I'm not qualified to provide medical advice. Please consult a licensed doctor, "
    "physiotherapist, nutritionist, or other appropriate healthcare professional."
)
OFF_TOPIC_REDIRECT = (
    "I'm a fitness assistant and can only help with fitness, workouts, exercise, nutrition, "
    "and healthy lifestyle questions."
)
ABUSIVE_REDIRECT = "Let's keep things respectful. I'm happy to help with any fitness, workout, or nutrition question you have."


def is_abusive(normalized_text: str) -> bool:
    return any(p.search(normalized_text) for p in _ABUSIVE_PATTERNS)


def is_medical(normalized_text: str) -> bool:
    return any(kw in normalized_text for kw in MEDICAL_KEYWORDS)


def is_false_identity_claim(reply_text: str) -> bool:
    """True if a generated reply claims the bot *is* Junaid rather than an
    AI he built — checked against the LLM's actual output (not just the
    user's message) since this specific small model volunteers this even
    on plain greetings, unprompted."""
    return bool(_FALSE_IDENTITY_CLAIM.search(reply_text))


def safety_check(text: str, *, is_roman_urdu: bool, intent: str) -> str | None:
    """Returns the fixed redirect string if text should never reach the
    LLM, or None if it's safe to generate.

    Roman Urdu is checked FIRST and hard-gated — the bot no longer attempts
    to understand or answer Roman Urdu at all, since the small fine-tuned
    model's Roman Urdu output was unreliable even when told to translate
    and reply in English. This is a deterministic gate, not a training
    bias, so it's 100% reliable regardless of what the LLM itself would
    have done.

    `bot_identity` is also hard-gated to a fixed answer for the same
    reason — the model's own sense of "am I an AI or the real Junaid" is
    unreliable (see is_false_identity_claim for the complementary
    post-generation check, which catches this even when the intent
    classifier doesn't flag it, e.g. on a plain "hello").

    Off-topic detection uses BOTH the keyword list AND the intent
    classifier's `off_topic_redirect` prediction — never an allow-list
    requiring a fitness keyword on every message.
    """
    if is_roman_urdu:
        return ENGLISH_ONLY_REDIRECT
    if intent == "bot_identity":
        return BOT_IDENTITY_REDIRECT

    normalized = normalize_for_matching(text)
    if any(kw in normalized for kw in PERSONAL_INFO_KEYWORDS):
        return PERSONAL_INFO_REDIRECT
    if any(kw in normalized for kw in CONTACT_KEYWORDS):
        return CONTACT_REDIRECT
    if is_abusive(normalized):
        return ABUSIVE_REDIRECT
    if is_medical(normalized):
        return MEDICAL_REDIRECT

    off_topic = any(kw in normalized for kw in OFF_TOPIC_KEYWORDS) or intent == "off_topic_redirect"
    if off_topic:
        return OFF_TOPIC_REDIRECT

    return None
